---

- name: create accounts tmpfs filesystem mount point
  file:
    dest: "{{ solana_accounts_location }}"
    owner: solana
    group: solana
    mode: "01777"
    state: directory

- name: mount accounts tmpfs
  mount:
    name: "{{ solana_accounts_location }}"
    src: tmpfs
    fstype: tmpfs
    opts: "size={{ solana_tmpfs_size }}"
    state: mounted
