---
- name: Install parted package if not installled
  become: true
  become_user: root
  action: >
         {{ ansible_pkg_mgr }} name={{ item }}  state=present update_cache=yes
  with_items:
       - parted

- name: Create a new ext4 primary partition
  community.general.parted:
          device: /dev/nvme0n1
          number: 1
          label: gpt
          state: present
          fs_type: ext4
- name: Format /dev/nvme0n1p1 ext4 partition
  shell: |
          mkfs.ext4 /dev/nvme0n1p1

- name: "Get UUID for partition"
  command: blkid -s PARTUUID -o value /dev/nvme0n1p1
  register: disk_blkid

- name: mount nvme0n1p1 partition
  ansible.posix.mount:
          path: /home/sol
          src: 'PARTUUID={{ disk_blkid.stdout }}'
          fstype: ext4
          opts: defaults
          state: mounted

- name: Copy /etc/skel files in /home/sol
  ansible.builtin.copy:
          src: '/etc/skel/{{ item }}'
          dest: '/home/sol/{{ item }}'
  with_items:
          - .bash_logout
          - .bashrc
          - .profile

- name: change /home/sol ownsership 
  ansible.builtin.file:
          path: /home/sol
          owner: sol
          group: sol
          mode: '0755'
          recurse: yes
          state: directory

- name: move script and sh files to sol users
  become: true
  become_user: sol
  synchronize:
          src: solana.solana-validator/test/
          dest: /home/sol
