---
- name: install UFW firewall
  apt:
          name: ufw
          state: present

- name: enable UFW service
  systemd:
          daemon_reload: true
          name: ufw
          enabled: yes

- name: Allow SSH  traffic
  community.general.ufw:
          rule: allow
          proto: tcp
          port: ssh
- name: Allow specific traffic
  community.general.ufw:
          rule: allow
          proto: "{{ item.protocol }}"
          port: "{{ item.port }}"
          src: "{{ item.sourceip }}"
  with_items:
          #          - {'protocol':'tcp','port':'22','sourceip':'0.0.0.0'}
          - {'protocol':'tcp','port':'80','sourceip':'0.0.0.0'}
          - {'protocol':'tcp','port':'443','sourceip':'0.0.0.0'}
          - {'protocol':'tcp','port':'8080','sourceip':'0.0.0.0'}
          - {'protocol':'tcp','port':'8443','sourceip':'0.0.0.0'}

- name: Enable UFW
  community.general.ufw:
          state: enabled
