---

- name: change /home/sol ownsership 
  ansible.builtin.file:
          path: /home/sol
          owner: sol
          group: sol
          mode: '0755'
          recurse: yes
          state: directory
- name: 
  become: yes
  become_user: sol
  file:
          name: /home/sol/pubkeys
          state: directory
# Configure solana key
- name: ensure solana key is present
  command: /home/sol/.local/share/solana/install/active_release/bin/solana-keygen new -o /home/sol/pubkeys/identity.json  --no-bip39-passphrase -s
  become: true
  become_user: sol
  args:
    chdir: /home/sol/pubkeys
    creates: /home/sol/pubkeys/identity.json
  when: (solana_keypairs is not defined or solana_keypairs|length == 0) and solana_generate_keypair

- name: ensure solana keys are present
  copy:
    content: "{{ item.key }}"
    dest: "/home/sol/pubkeys/{{ item.name }}.json"
    owner: sol
    group: sol
    mode: 0600
  with_items: "{{ solana_keypairs }}"
  when: solana_keypairs is defined

- name: set keypair to default
  command: /home/sol/.local/share/solana/install/active_release/bin/solana config set --keypair "{{ solana_public_key }}"
  become: true
  become_user: sol
  args:
    chdir: /home/sol/pubkeys

- name: check solana pubkey
  command: /home/sol/.local/share/solana/install/active_release/bin/solana-keygen pubkey "{{ solana_public_key }}"
  register: res_pubkey

- name: save public key hash
  set_fact:
    solana_public_key_hash: "{{ res_pubkey.stdout }}"


